import type { RoomSpec, RoomType } from './types';

/** Window-to-floor-area ratio per NBC (minimum openable area / floor area) */
export const WINDOW_FLOOR_RATIO = {
  habitable: 1 / 8,
  kitchen: 1 / 8,
  bathroom: 1 / 20,
  toilet: 0,
  staircase: 1 / 16,
} as const;

// Default room templates used to seed room specs.
export const DEFAULT_ROOM_SPECS: Record<RoomType, Partial<RoomSpec>> = {
  living: {
    minArea: 15,
    preferredArea: 22,
    maxArea: 35,
    minWidth: 3.6,
    minHeight: 3.0,
    requiresWindow: true,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'essential',
  },
  dining: {
    minArea: 10,
    preferredArea: 14,
    maxArea: 20,
    minWidth: 3.0,
    minHeight: 3.0,
    requiresWindow: true,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'important',
  },
  kitchen: {
    minArea: 7,
    preferredArea: 10,
    maxArea: 16,
    minWidth: 2.4,
    minHeight: 3.0,
    requiresWindow: true,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'essential',
  },
  master_bedroom: {
    minArea: 14,
    preferredArea: 18,
    maxArea: 25,
    minWidth: 3.6,
    minHeight: 3.0,
    requiresWindow: true,
    requiresVentilation: true,
    requiresAttachedBath: true,
    priority: 'essential',
  },
  bedroom: {
    minArea: 10,
    preferredArea: 13,
    maxArea: 18,
    minWidth: 3.0,
    minHeight: 3.0,
    requiresWindow: true,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'essential',
  },
  bathroom: {
    minArea: 3.5,
    preferredArea: 5,
    maxArea: 8,
    minWidth: 1.8,
    minHeight: 3.0,
    requiresWindow: true,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'essential',
  },
  toilet: {
    minArea: 1.5,
    preferredArea: 2.5,
    maxArea: 4,
    minWidth: 1.2,
    minHeight: 3.0,
    requiresWindow: false,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'essential',
  },
  pooja: {
    minArea: 3,
    preferredArea: 5,
    maxArea: 8,
    minWidth: 1.5,
    minHeight: 3.0,
    requiresWindow: false,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'desirable',
  },
  study: {
    minArea: 6,
    preferredArea: 9,
    maxArea: 14,
    minWidth: 2.4,
    minHeight: 3.0,
    requiresWindow: true,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'desirable',
  },
  home_office: {
    minArea: 8,
    preferredArea: 12,
    maxArea: 18,
    minWidth: 2.7,
    minHeight: 3.0,
    requiresWindow: true,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'desirable',
  },
  store: {
    minArea: 3,
    preferredArea: 5,
    maxArea: 8,
    minWidth: 1.5,
    minHeight: 3.0,
    requiresWindow: false,
    requiresVentilation: false,
    requiresAttachedBath: false,
    priority: 'important',
  },
  utility: {
    minArea: 3,
    preferredArea: 5,
    maxArea: 8,
    minWidth: 1.5,
    minHeight: 3.0,
    requiresWindow: false,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'important',
  },
  laundry: {
    minArea: 4,
    preferredArea: 6,
    maxArea: 10,
    minWidth: 2.0,
    minHeight: 3.0,
    requiresWindow: true,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'desirable',
  },
  garage: {
    minArea: 15,
    preferredArea: 20,
    maxArea: 30,
    minWidth: 3.0,
    minHeight: 2.7,
    requiresWindow: false,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'desirable',
  },
  parking: {
    minArea: 12,
    preferredArea: 18,
    maxArea: 30,
    minWidth: 2.5,
    minHeight: 2.7,
    requiresWindow: false,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'desirable',
  },
  balcony: {
    minArea: 3,
    preferredArea: 5,
    maxArea: 12,
    minWidth: 1.2,
    minHeight: 3.0,
    requiresWindow: false,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'desirable',
  },
  terrace: {
    minArea: 10,
    preferredArea: 20,
    maxArea: 50,
    minWidth: 3.0,
    minHeight: 0,
    requiresWindow: false,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'optional',
  },
  corridor: {
    minArea: 3,
    preferredArea: 4,
    maxArea: 8,
    minWidth: 1.2,
    minHeight: 3.0,
    requiresWindow: false,
    requiresVentilation: false,
    requiresAttachedBath: false,
    priority: 'essential',
  },
  staircase: {
    minArea: 6,
    preferredArea: 8,
    maxArea: 12,
    minWidth: 1.2,
    minHeight: 3.0,
    requiresWindow: false,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'essential',
  },
  lift: {
    minArea: 3,
    preferredArea: 4,
    maxArea: 6,
    minWidth: 1.5,
    minHeight: 3.0,
    requiresWindow: false,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'optional',
  },
  entrance_lobby: {
    minArea: 4,
    preferredArea: 6,
    maxArea: 12,
    minWidth: 1.8,
    minHeight: 3.0,
    requiresWindow: false,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'important',
  },
  drawing_room: {
    minArea: 14,
    preferredArea: 20,
    maxArea: 30,
    minWidth: 3.6,
    minHeight: 3.0,
    requiresWindow: true,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'desirable',
  },
  guest_room: {
    minArea: 10,
    preferredArea: 14,
    maxArea: 20,
    minWidth: 3.0,
    minHeight: 3.0,
    requiresWindow: true,
    requiresVentilation: true,
    requiresAttachedBath: true,
    priority: 'desirable',
  },
  servants_quarter: {
    minArea: 8,
    preferredArea: 10,
    maxArea: 14,
    minWidth: 2.4,
    minHeight: 2.7,
    requiresWindow: true,
    requiresVentilation: true,
    requiresAttachedBath: true,
    priority: 'optional',
  },
  pantry: {
    minArea: 3,
    preferredArea: 5,
    maxArea: 8,
    minWidth: 1.5,
    minHeight: 3.0,
    requiresWindow: false,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'desirable',
  },
  gym: {
    minArea: 12,
    preferredArea: 18,
    maxArea: 30,
    minWidth: 3.0,
    minHeight: 3.0,
    requiresWindow: true,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'optional',
  },
  home_theater: {
    minArea: 15,
    preferredArea: 22,
    maxArea: 35,
    minWidth: 3.6,
    minHeight: 3.0,
    requiresWindow: false,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'optional',
  },
  swimming_pool: {
    minArea: 20,
    preferredArea: 35,
    maxArea: 60,
    minWidth: 4.0,
    minHeight: 0,
    requiresWindow: false,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'optional',
  },
  garden: {
    minArea: 10,
    preferredArea: 25,
    maxArea: 100,
    minWidth: 3.0,
    minHeight: 0,
    requiresWindow: false,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'desirable',
  },
  sit_out: {
    minArea: 4,
    preferredArea: 6,
    maxArea: 12,
    minWidth: 1.5,
    minHeight: 0,
    requiresWindow: false,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'desirable',
  },
  verandah: {
    minArea: 5,
    preferredArea: 8,
    maxArea: 15,
    minWidth: 1.8,
    minHeight: 3.0,
    requiresWindow: false,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'desirable',
  },
  foyer: {
    minArea: 4,
    preferredArea: 6,
    maxArea: 10,
    minWidth: 1.8,
    minHeight: 3.0,
    requiresWindow: false,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'desirable',
  },
  walk_in_closet: {
    minArea: 4,
    preferredArea: 6,
    maxArea: 10,
    minWidth: 1.8,
    minHeight: 3.0,
    requiresWindow: false,
    requiresVentilation: false,
    requiresAttachedBath: false,
    priority: 'desirable',
  },
  dressing: {
    minArea: 4,
    preferredArea: 6,
    maxArea: 10,
    minWidth: 1.8,
    minHeight: 3.0,
    requiresWindow: false,
    requiresVentilation: false,
    requiresAttachedBath: false,
    priority: 'desirable',
  },
  childrens_room: {
    minArea: 10,
    preferredArea: 14,
    maxArea: 18,
    minWidth: 3.0,
    minHeight: 3.0,
    requiresWindow: true,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'important',
  },
  library: {
    minArea: 8,
    preferredArea: 12,
    maxArea: 20,
    minWidth: 2.7,
    minHeight: 3.0,
    requiresWindow: true,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'optional',
  },
  workshop: {
    minArea: 10,
    preferredArea: 15,
    maxArea: 25,
    minWidth: 3.0,
    minHeight: 3.0,
    requiresWindow: true,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'optional',
  },
  basement: {
    minArea: 30,
    preferredArea: 50,
    maxArea: 200,
    minWidth: 5.0,
    minHeight: 2.7,
    requiresWindow: false,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'optional',
  },
  mechanical_room: {
    minArea: 4,
    preferredArea: 6,
    maxArea: 10,
    minWidth: 2.0,
    minHeight: 3.0,
    requiresWindow: false,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'important',
  },
  electrical_panel: {
    minArea: 1.5,
    preferredArea: 2,
    maxArea: 4,
    minWidth: 0.8,
    minHeight: 3.0,
    requiresWindow: false,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'essential',
  },
  water_tank_room: {
    minArea: 3,
    preferredArea: 4,
    maxArea: 8,
    minWidth: 1.5,
    minHeight: 2.4,
    requiresWindow: false,
    requiresVentilation: true,
    requiresAttachedBath: false,
    priority: 'important',
  },
};

export const ROOM_COLORS: Record<RoomType, string> = {
  living: '#E0F2FE',
  dining: '#FEF3C7',
  kitchen: '#FEE2E2',
  master_bedroom: '#E0E7FF',
  bedroom: '#DBEAFE',
  bathroom: '#D1FAE5',
  toilet: '#D1FAE5',
  pooja: '#FEF9C3',
  study: '#F3E8FF',
  home_office: '#E0E7FF',
  store: '#F5F5F4',
  utility: '#E5E7EB',
  laundry: '#CFFAFE',
  garage: '#D1D5DB',
  parking: '#D1D5DB',
  balcony: '#ECFDF5',
  terrace: '#F0FDF4',
  corridor: '#F9FAFB',
  staircase: '#FED7AA',
  lift: '#FED7AA',
  entrance_lobby: '#FBCFE8',
  drawing_room: '#E0F2FE',
  guest_room: '#DDD6FE',
  servants_quarter: '#E5E7EB',
  pantry: '#FEF3C7',
  gym: '#FEE2E2',
  home_theater: '#1F2937',
  swimming_pool: '#BAE6FD',
  garden: '#BBF7D0',
  sit_out: '#ECFDF5',
  verandah: '#F0FDF4',
  foyer: '#FBCFE8',
  walk_in_closet: '#F3E8FF',
  dressing: '#F3E8FF',
  childrens_room: '#FDE68A',
  library: '#E0E7FF',
  workshop: '#E5E7EB',
  basement: '#9CA3AF',
  mechanical_room: '#6B7280',
  electrical_panel: '#FCA5A5',
  water_tank_room: '#93C5FD',
};