#!/bin/bash
echo "🧪 Testing Authentication & API Fixes Locally"
echo "=============================================="
echo ""
echo "Starting backends:"
echo "  1. Node.js API (port 3001)"
echo "  2. Python API (port 8000)"
echo ""
echo "Then access: http://localhost:5173/app"
echo ""
echo "Expected fixes:"
echo "  ✅ No more 403 Forbidden on /api/user/login"
echo "  ✅ No more 404 on /api/user/tier (now /api/user/limits)"
echo "  ✅ No more 401 on /sections/standard/create"
echo "  ✅ Canvas renders with optional WebGL warning"
echo ""
echo "Run in 3 terminals:"
echo "  Terminal 1: pnpm --filter @beamlab/api dev"
echo "  Terminal 2: cd apps/backend-python && source .venv/bin/activate && uvicorn main:app --reload"
echo "  Terminal 3: pnpm --filter @beamlab/web dev"
