/**
 * WorkspaceDemo - Demo page showing the new Engineering Workspace
 * Temporary page to demonstrate the advanced UI templates
 */

import { FC, useState } from 'react';
import { Link } from 'react-router-dom';
import {
    EngineeringWorkspace,
    ViewportPanel,
    PropertiesPanel,
    ResultsPanel,
} from '../components/workspace';
import { DataTable, StatusBadge } from '../components/ui';

// PDF report generation handler
const generatePDFReport = () => {
  const html = `
    <html>
      <head>
        <title>Structural Analysis Report</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 20px; color: #333; }
          h1 { color: #1f2937; margin-bottom: 10px; }
          h2 { color: #4b5563; margin-top: 20px; margin-bottom: 10px; border-bottom: 2px solid #667eea; padding-bottom: 5px; }
          table { width: 100%; border-collapse: collapse; margin: 15px 0; }
          th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
          th { background-color: #667eea; color: white; }
          tr:nth-child(even) { background-color: #f9fafb; }
          .section { margin: 20px 0; page-break-inside: avoid; }
          .summary { background-color: #f0f4ff; padding: 15px; border-radius: 5px; margin: 15px 0; }
        </style>
      </head>
      <body>
        <h1>Structural Analysis Report</h1>
        <div class="summary">
          <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
          <p><strong>Analysis Type:</strong> Linear Static</p>
          <p><strong>Status:</strong> ✓ Completed</p>
        </div>
        
        <div class="section">
          <h2>Model Summary</h2>
          <table>
            <tr><th>Parameter</th><th>Value</th></tr>
            <tr><td>Number of Nodes</td><td>6</td></tr>
            <tr><td>Number of Members</td><td>8</td></tr>
            <tr><td>Degrees of Freedom</td><td>12</td></tr>
            <tr><td>Load Cases</td><td>2 (DL, LL)</td></tr>
          </table>
        </div>
        
        <div class="section">
          <h2>Support Reactions</h2>
          <table>
            <tr><th>Node</th><th>Load Case</th><th>Fx (kN)</th><th>Fy (kN)</th><th>Fz (kN)</th><th>Status</th></tr>
            <tr><td>N1</td><td>DL</td><td>0.0</td><td>-125.4</td><td>0.0</td><td>PASS</td></tr>
            <tr><td>N2</td><td>DL</td><td>0.0</td><td>-98.7</td><td>0.0</td><td>PASS</td></tr>
            <tr><td>N3</td><td>LL</td><td>-15.2</td><td>-203.1</td><td>0.0</td><td>OK</td></tr>
          </table>
        </div>
        
        <div class="section">
          <h2>Notes</h2>
          <p>Analysis completed successfully. All constraints satisfied.</p>
        </div>
        
        <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #999; font-size: 12px;">
          Generated by BeamLab Ultimate | ${new Date().toLocaleString()}
        </footer>
      </body>
    </html>
  `;
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `Report-${new Date().getTime()}.html`;
  a.click();
  URL.revokeObjectURL(url);
};

// Sample data for demonstration
const sampleReactions = [
    { node: 'N1', lc: 'DL', fx: 0.0, fy: -125.4, fz: 0.0, status: 'pass' as const },
    { node: 'N2', lc: 'DL', fx: 0.0, fy: -98.7, fz: 0.0, status: 'pass' as const },
    { node: 'N3', lc: 'LL', fx: -15.2, fy: -203.1, fz: 0.0, status: 'warning' as const },
    { node: 'N4', lc: 'LL', fx: 15.2, fy: -189.5, fz: 0.0, status: 'pass' as const },
];

const sampleForces = [
    { member: 'M1', axial: -145.2, shear: 23.1, moment: 45.8, status: 'pass' as const },
    { member: 'M2', axial: -132.6, shear: -18.4, moment: -38.2, status: 'pass' as const },
    { member: 'M3', axial: -98.4, shear: 42.7, moment: 89.3, status: 'fail' as const },
];

export const WorkspaceDemo: FC = () => {
    const [showTutorial, setShowTutorial] = useState(false);
    const [selectedSection, setSelectedSection] = useState('W12x26');
    const [selectedMaterial, setSelectedMaterial] = useState('A992');

    return (
        <EngineeringWorkspace
            showTutorial={showTutorial}
            onTutorialClose={() => setShowTutorial(false)}
            propertiesPanel={
                <PropertiesPanel
                    title="Properties"
                    sections={[
                        {
                            id: 'member',
                            title: 'Member Properties',
                            badge: 'M-102',
                            defaultOpen: true,
                            content: (
                                <div className="space-y-3">
                                    <div>
                                        <label className="text-xs text-[#869ab8] block mb-1">Material</label>
                                        <select
                                            value={selectedMaterial}
                                            onChange={(e) => setSelectedMaterial(e.target.value)}
                                            className="w-full bg-[#0b1326] border border-[#1a2333] rounded px-2 py-1.5 text-sm text-[#dae2fd] focus:border-blue-500 focus:outline-none"
                                        >
                                            <option value="A992">Steel A992</option>
                                            <option value="A36">Steel A36</option>
                                            <option value="A572">Steel A572 Gr. 50</option>
                                        </select>
                                    </div>
                                    <div>
                                        <label className="text-xs text-[#869ab8] block mb-1">Section</label>
                                        <select
                                            value={selectedSection}
                                            onChange={(e) => setSelectedSection(e.target.value)}
                                            className="w-full bg-[#0b1326] border border-[#1a2333] rounded px-2 py-1.5 text-sm text-[#dae2fd] focus:border-blue-500 focus:outline-none"
                                        >
                                            <option value="W12x26">W12x26</option>
                                            <option value="W14x22">W14x22</option>
                                            <option value="W16x31">W16x31</option>
                                            <option value="W18x35">W18x35</option>
                                        </select>
                                    </div>
                                    <div className="pt-2 border-t border-[#1a2333]">
                                        <div className="text-xs text-[#869ab8] mb-2">Properties</div>
                                        <div className="space-y-1 text-xs font-mono">
                                            <div className="flex justify-between">
                                                <span className="text-[#869ab8]">A:</span>
                                                <span className="text-[#dae2fd]">7.65 in²</span>
                                            </div>
                                            <div className="flex justify-between">
                                                <span className="text-[#869ab8]">I<sub>x</sub>:</span>
                                                <span className="text-[#dae2fd]">204 in⁴</span>
                                            </div>
                                            <div className="flex justify-between">
                                                <span className="text-[#869ab8]">S<sub>x</sub>:</span>
                                                <span className="text-[#dae2fd]">33.4 in³</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            ),
                        },
                        {
                            id: 'loads',
                            title: 'Active Loads',
                            badge: '3',
                            defaultOpen: false,
                            content: (
                                <div className="space-y-2">
                                    <div className="flex items-center justify-between text-xs">
                                        <span className="text-slate-600 dark:text-slate-300">DL (Dead Load)</span>
                                        <span className="text-green-400">Active</span>
                                    </div>
                                    <div className="flex items-center justify-between text-xs">
                                        <span className="text-slate-600 dark:text-slate-300">LL (Live Load)</span>
                                        <span className="text-green-400">Active</span>
                                    </div>
                                    <div className="flex items-center justify-between text-xs">
                                        <span className="text-slate-600 dark:text-slate-300">EQ (Earthquake)</span>
                                        <span className="text-[#869ab8]">Inactive</span>
                                    </div>
                                </div>
                            ),
                        },
                        {
                            id: 'analysis',
                            title: 'Analysis Settings',
                            defaultOpen: false,
                            content: (
                                <div className="space-y-2 text-xs">
                                    <div className="flex items-center justify-between">
                                        <span className="text-[#869ab8]">Type:</span>
                                        <span className="text-[#dae2fd]">Linear Static</span>
                                    </div>
                                    <div className="flex items-center justify-between">
                                        <span className="text-[#869ab8]">Solver:</span>
                                        <span className="text-[#dae2fd]">Direct</span>
                                    </div>
                                    <div className="flex items-center justify-between">
                                        <span className="text-[#869ab8]">P-Delta:</span>
                                        <span className="text-blue-400">Enabled</span>
                                    </div>
                                </div>
                            ),
                        },
                    ]}
                />
            }
            resultsPanel={
                <ResultsPanel
                    tabs={[
                        {
                            id: 'reactions',
                            label: 'Reactions',
                            badge: sampleReactions.length,
                            content: (
                                <div className="p-2">
                                    <DataTable
                                        columns={[
                                            { accessor: 'node', header: 'Node' },
                                            { accessor: 'lc', header: 'LC' },
                                            {
                                                accessor: 'fx',
                                                header: 'FX (kN)',
                                                cell: ({ row }: { row: { original: typeof sampleReactions[0] } }) => (
                                                    <span className={row.original.fx === 0 ? 'text-slate-500' : 'text-[#dae2fd]'}>
                                                        {row.original.fx.toFixed(1)}
                                                    </span>
                                                ),
                                            },
                                            {
                                                accessor: 'fy',
                                                header: 'FY (kN)',
                                                cell: ({ row }: { row: { original: typeof sampleReactions[0] } }) => (
                                                    <span className="text-[#dae2fd] font-semibold">{row.original.fy.toFixed(1)}</span>
                                                ),
                                            },
                                            {
                                                accessor: 'fz',
                                                header: 'FZ (kN)',
                                                cell: ({ row }: { row: { original: typeof sampleReactions[0] } }) => (
                                                    <span className={row.original.fz === 0 ? 'text-slate-500' : 'text-[#dae2fd]'}>
                                                        {row.original.fz.toFixed(1)}
                                                    </span>
                                                ),
                                            },
                                            {
                                                accessor: 'status',
                                                header: 'Status',
                                                cell: ({ row }: { row: { original: typeof sampleReactions[0] } }) => (
                                                    <StatusBadge variant={row.original.status} size="sm">
                                                        {row.original.status.toUpperCase()}
                                                    </StatusBadge>
                                                ),
                                            },
                                        ]}
                                        data={sampleReactions}
                                        highlightRow={(row) => row.status === 'warning' ? 'bg-yellow-500/10' : false}
                                        compact
                                    />
                                </div>
                            ),
                        },
                        {
                            id: 'forces',
                            label: 'Member Forces',
                            badge: sampleForces.length,
                            content: (
                                <div className="p-2">
                                    <DataTable
                                        columns={[
                                            { accessor: 'member', header: 'Member' },
                                            {
                                                accessor: 'axial',
                                                header: 'Axial (kN)',
                                                cell: ({ row }: { row: { original: typeof sampleForces[0] } }) => (
                                                    <span className={row.original.axial < 0 ? 'text-blue-400' : 'text-red-400'}>
                                                        {row.original.axial.toFixed(1)}
                                                    </span>
                                                ),
                                            },
                                            { accessor: 'shear', header: 'Shear (kN)', cell: ({ row }: { row: { original: typeof sampleForces[0] } }) => row.original.shear.toFixed(1) },
                                            { accessor: 'moment', header: 'Moment (kN·m)', cell: ({ row }: { row: { original: typeof sampleForces[0] } }) => row.original.moment.toFixed(1) },
                                            {
                                                accessor: 'status',
                                                header: 'Check',
                                                cell: ({ row }: { row: { original: typeof sampleForces[0] } }) => (
                                                    <StatusBadge variant={row.original.status} size="sm">
                                                        {row.original.status === 'pass' ? '✓' : '✗'}
                                                    </StatusBadge>
                                                ),
                                            },
                                        ]}
                                        data={sampleForces}
                                        highlightRow={(row) => row.status === 'fail' ? 'bg-red-900/10' : false}
                                        compact
                                    />
                                </div>
                            ),
                        },
                        {
                            id: 'report',
                            label: 'Report',
                            content: (
                                <div className="p-4 text-center">
                                    <div className="flex flex-col items-center gap-3">
                                        <span className="material-symbols-outlined text-5xl text-slate-700">description</span>
                                        <p className="text-sm text-[#869ab8]">Generate PDF Report</p>
                                        <button 
                                          type="button" 
                                          onClick={generatePDFReport}
                                          className="px-6 py-2 bg-gradient-to-r from-[#4d8eff] to-[#3b72cc] hover:from-[#3b72cc] hover:to-[#2a5599] text-white shadow-[0_0_15px_rgba(77,142,255,0.3)] hover:shadow-[0_0_20px_rgba(77,142,255,0.5)] rounded text-sm font-semibold transition-colors">
                                            Download PDF Report
                                        </button>
                                    </div>
                                </div>
                            ),
                        },
                    ]}
                />
            }
        >
            <ViewportPanel
                coordinates={{ x: 0, y: 0, z: 0 }}
                showGrid
                showAxes
                overlayInfo={[
                    { label: 'Material', value: selectedMaterial },
                    { label: 'Section', value: selectedSection },
                    { label: 'Length', value: '6.0 m' },
                ]}
            >
                {/* Placeholder for 3D viewport */}
                <div className="w-full h-full flex flex-col items-center justify-center gap-6">
                    <span className="material-symbols-outlined text-[120px] text-slate-700">deployed_code</span>
                    <div className="text-center">
                        <h2 className="text-2xl font-bold tracking-tight text-[#869ab8] mb-2">
                            3D Viewport Ready
                        </h2>
                        <p className="text-sm text-slate-500 max-w-md">
                            The workspace layout is complete. Integrate your Three.js canvas here to display the structural model.
                        </p>
                        <Link
                            to="/demo"
                            className="inline-block mt-6 px-6 py-3 bg-gradient-to-r from-[#4d8eff] to-[#3b72cc] hover:from-[#3b72cc] hover:to-[#2a5599] text-white shadow-[0_0_15px_rgba(77,142,255,0.3)] hover:shadow-[0_0_20px_rgba(77,142,255,0.5)] rounded-lg font-semibold transition-colors"
                        >
                            Go to Actual Demo →
                        </Link>
                    </div>
                    <button type="button"
                        onClick={() => setShowTutorial(true)}
                        className="text-xs text-[#869ab8] hover:text-slate-600 dark:hover:text-slate-300 underline"
                    >
                        Show Tutorial Modal
                    </button>
                </div>
            </ViewportPanel>
        </EngineeringWorkspace>
    );
};

export default WorkspaceDemo;
