
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { AnalysisResults } from '../store/model';
import { SteelDesignResults } from './SteelDesignService';

interface ProjectInfo {
    name: string;
    engineer: string;
    date: string;
    description: string;
}

export const generateDesignReport = (
    project: ProjectInfo,
    members: any[],
    nodes: any[],
    analysisResults: AnalysisResults | null,
    designResults: Map<string, SteelDesignResults>
) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // Helper for formatting
    const formatNumber = (n: number) => n.toFixed(2);

    // ============================================
    // HEADER
    // ============================================
    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40);
    doc.text("BeamLab Ultimate", 14, 20);

    doc.setFontSize(14);
    doc.setTextColor(100, 100, 100);
    doc.text("Structural Analysis & Design Report", 14, 28);

    // Project Details
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(`Project: ${project.name}`, 14, 40);
    doc.text(`Engineer: ${project.engineer}`, 14, 45);
    doc.text(`Date: ${project.date}`, 14, 50);
    doc.line(14, 55, pageWidth - 14, 55);

    // ============================================
    // MODEL SUMMARY
    // ============================================
    doc.setFontSize(14);
    doc.text("1. Model Summary", 14, 65);

    const summaryData = [
        ['Nodes', nodes.length],
        ['Members', members.length],
        ['Analysis Status', analysisResults ? 'Completed' : 'Not Run'],
        ['Design Check Status', designResults.size > 0 ? 'Completed' : 'Not Run']
    ];

    autoTable(doc, {
        startY: 70,
        head: [['Item', 'Count/Status']],
        body: summaryData,
        theme: 'striped',
        headStyles: { fillColor: [63, 81, 181] },
        styles: { fontSize: 10 }
    });

    // ============================================
    // ANALYSIS RESULTS (FORCES)
    // ============================================
    if (analysisResults) {
        let finalY = (doc as any).lastAutoTable.finalY + 15;
        doc.setFontSize(14);
        doc.text("2. Analysis Results (Member Forces)", 14, finalY);

        const forcesBody = Array.from(analysisResults.memberForces.entries()).map(([id, f]) => [
            `M${id}`,
            formatNumber(f.axial),
            formatNumber(f.shearY),
            formatNumber(f.shearZ),
            formatNumber(f.momentY),
            formatNumber(f.momentZ)
        ]);

        autoTable(doc, {
            startY: finalY + 5,
            head: [['Member', 'Axial (kN)', 'Vy (kN)', 'Vz (kN)', 'My (kNm)', 'Mz (kNm)']],
            body: forcesBody,
            theme: 'grid',
            headStyles: { fillColor: [63, 81, 181] },
            styles: { fontSize: 9 }
        });
    }

    // ============================================
    // DESIGN CHECKS
    // ============================================
    if (designResults.size > 0) {
        let finalY = (doc as any).lastAutoTable.finalY + 15;

        // New page if needed
        if (finalY > 250) {
            doc.addPage();
            finalY = 20;
        }

        doc.setFontSize(14);
        doc.text("3. Steel Design Checks (AISC 360-16)", 14, finalY);

        const designBody = Array.from(designResults.values()).map(r => [
            `M${r.memberId}`,
            r.section.name,
            (r.criticalRatio * 100).toFixed(1) + '%',
            r.overallStatus,
            r.governingCheck
        ]);

        autoTable(doc, {
            startY: finalY + 5,
            head: [['Member', 'Section', 'Ratio', 'Status', 'Critical Check']],
            body: designBody,
            theme: 'grid',
            headStyles: { fillColor: [0, 150, 136] }, // Teal info
            columnStyles: {
                3: { fontStyle: 'bold' }
            },
            didParseCell: (data) => {
                if (data.section === 'body' && data.column.index === 3) {
                    const status = data.cell.raw;
                    if (status === 'FAIL') data.cell.styles.textColor = [220, 50, 50];
                    else if (status === 'WARNING') data.cell.styles.textColor = [220, 180, 50];
                    else data.cell.styles.textColor = [50, 180, 50];
                }
            }
        });
    }

    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Page ${i} of ${pageCount} - Generated by BeamLab Ultimate`, pageWidth / 2, doc.internal.pageSize.height - 10, { align: 'center' });
    }

    // Save
    doc.save(`BeamLab_Report_${project.name.replace(/\s+/g, '_')}.pdf`);
};
