
import { ProjectInfo, AnalysisResults, Node, Member } from '../store/model';
import { SteelDesignResults } from './SteelDesignService';

// Standard density of steel (kg/m³)
const STEEL_DENSITY = 7850;

export interface BOMItem {
    section: string;
    count: number;
    totalLength: number; // meters
    unitWeight: number; // kg/m
    totalWeight: number; // kg
    costPerTon?: number; // Estimated cost
}

export interface BOMSummary {
    items: BOMItem[];
    totalWeight: number; // kg
    totalCost: number; // Currency
}

export const ReportingService = {

    /**
     * Calculate Bill of Materials (BOM)
     */
    generateBOM(members: Member[], nodes: Map<string, Node>, costPerTon: number = 1200): BOMSummary {
        const bomMap = new Map<string, BOMItem>();

        members.forEach(member => {
            const start = nodes.get(member.startNodeId);
            const end = nodes.get(member.endNodeId);
            if (!start || !end) return;

            const length = Math.sqrt(
                Math.pow(end.x - start.x, 2) +
                Math.pow(end.y - start.y, 2) +
                Math.pow((end.z || 0) - (start.z || 0), 2)
            );

            const sectionName = member.sectionId || 'Unknown Section';
            // Estimate Area if not provided (fallback for demo) or use real property
            const area = member.A || 0.005; // Default 50cm2 area if missing
            const unitWeight = area * STEEL_DENSITY;

            if (!bomMap.has(sectionName)) {
                bomMap.set(sectionName, {
                    section: sectionName,
                    count: 0,
                    totalLength: 0,
                    unitWeight: unitWeight,
                    totalWeight: 0
                });
            }

            const item = bomMap.get(sectionName)!;
            item.count++;
            item.totalLength += length;
            item.totalWeight += length * unitWeight;
        });

        const items = Array.from(bomMap.values());
        const totalWeight = items.reduce((sum, item) => sum + item.totalWeight, 0);
        const totalCost = (totalWeight / 1000) * costPerTon; // Cost per Ton

        return { items, totalWeight, totalCost };
    },

    /**
     * Generate Detailed Calculation Book (PDF)
     */
    async generateCalculationBook(
        project: ProjectInfo,
        nodes: Map<string, Node>,
        members: Map<string, Member>,
        analysisResults: AnalysisResults | null,
        designResults: Map<string, SteelDesignResults> | null
    ) {
        const [{ default: jsPDF }, { default: autoTable }] = await Promise.all([
          import('jspdf'),
          import('jspdf-autotable'),
        ]);
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.width;
        const pageHeight = doc.internal.pageSize.height;
        let currentPage = 1;

        // --- Helper: Header & Footer ---
        const addHeaderFooter = () => {
            doc.setFontSize(10);
            doc.setTextColor(150);
            doc.text(`Project: ${project.name}`, 14, 10);
            doc.text(`Page ${currentPage}`, pageWidth - 20, 10);
            doc.line(14, 12, pageWidth - 14, 12);

            doc.text("Generated by BeamLab", pageWidth / 2, pageHeight - 10, { align: 'center' });
        };

        const checkPageBreak = (yData: number) => {
            if (yData > pageHeight - 30) {
                doc.addPage();
                currentPage++;
                addHeaderFooter();
                return 20; // Reset Y
            }
            return yData;
        };

        // --- TITLE PAGE ---
        doc.setFont("helvetica", "bold");
        doc.setFontSize(26);
        doc.setTextColor(40, 40, 40);
        doc.text("STRUCTURAL CALCULATION BOOK", pageWidth / 2, 80, { align: "center" });

        doc.setFontSize(16);
        doc.setFont("helvetica", "normal");
        doc.text(project.name, pageWidth / 2, 100, { align: "center" });

        doc.setFontSize(12);
        doc.text(`Client: ${project.client || 'N/A'}`, pageWidth / 2, 120, { align: "center" });
        doc.text(`Engineer: ${project.engineer || 'N/A'}`, pageWidth / 2, 128, { align: "center" });
        doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth / 2, 136, { align: "center" });
        doc.text(`Job No: ${project.jobNo || 'N/A'}`, pageWidth / 2, 144, { align: "center" });

        doc.addPage();
        currentPage++;
        addHeaderFooter();

        let finalY = 20;

        // --- 1. BILL OF MATERIALS ---
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(0, 0, 0);
        doc.text("1. Bill of Materials (BOM)", 14, finalY);
        finalY += 10;

        const bom = this.generateBOM(Array.from(members.values()), nodes);

        const bomTableData = bom.items.map(item => [
            item.section,
            item.count.toString(),
            item.totalLength.toFixed(2),
            item.unitWeight.toFixed(2),
            item.totalWeight.toFixed(1)
        ]);

        // Add Totals Row
        bomTableData.push([
            "TOTAL",
            Array.from(members.values()).length.toString(),
            "-",
            "-",
            bom.totalWeight.toFixed(1)
        ]);

        autoTable(doc, {
            startY: finalY,
            head: [['Section Profile', 'Count', 'Total Length (m)', 'Unit Wt (kg/m)', 'Total Wt (kg)']],
            body: bomTableData,
            theme: 'grid',
            headStyles: { fillColor: [41, 128, 185], textColor: 255 },
            foot: [['', '', '', 'Est. Cost ($):', `$${bom.totalCost.toFixed(2)}`]],
            footStyles: { fillColor: [240, 240, 240], textColor: 0, fontStyle: 'bold' }
        });

        finalY = (doc as any).lastAutoTable.finalY + 15;

        // --- 2. ANALYSIS RESULTS ---
        if (analysisResults) {
            finalY = checkPageBreak(finalY);
            doc.text("2. Analysis Results Summary", 14, finalY);
            finalY += 10;

            const resultsData = Array.from(members.values()).map(m => {
                const f = analysisResults.memberForces.get(m.id);
                const d = analysisResults.displacements.get(m.startNodeId); // Approx
                return [
                    m.id,
                    f ? f.axial.toFixed(1) : '-',
                    f ? f.shearY.toFixed(1) : '-',
                    f ? f.momentZ.toFixed(1) : '-',
                    d ? (Math.sqrt(d.dx * d.dx + d.dy * d.dy) * 1000).toFixed(1) : '-'
                ];
            });

            autoTable(doc, {
                startY: finalY,
                head: [['Mem ID', 'Axial (kN)', 'Shear Y (kN)', 'Moment Z (kNm)', 'Disp (mm)']],
                body: resultsData.slice(0, 50), // Limit for brevity in this method
                theme: 'striped',
                styles: { fontSize: 8 },
                headStyles: { fillColor: [46, 204, 113] }
            });

            finalY = (doc as any).lastAutoTable.finalY + 10;

            if (resultsData.length > 50) {
                doc.setFontSize(10);
                doc.setFont("helvetica", "italic");
                doc.text(`...(${resultsData.length - 50} more members truncated for summary)...`, 14, finalY);
                finalY += 10;
            }
        }

        // --- 3. DESIGN CHECKS ---
        if (designResults && designResults.size > 0) {
            finalY = checkPageBreak(finalY + 20);
            doc.setFontSize(14);
            doc.setFont("helvetica", "bold");
            doc.text("3. Design Verification (AISC 360-16)", 14, finalY);
            finalY += 10;

            const checkData = Array.from(designResults.values()).map(r => [
                r.memberId,
                r.section.name,
                r.governingCheck,
                (r.criticalRatio).toFixed(2),
                r.overallStatus
            ]);

            autoTable(doc, {
                startY: finalY,
                head: [['Mem ID', 'Section', 'Critical Check', 'Ratio', 'Status']],
                body: checkData,
                theme: 'grid',
                headStyles: { fillColor: [231, 76, 60] },
                didParseCell: (data) => {
                    if (data.section === 'body' && data.column.index === 4) {
                        const status = data.cell.raw;
                        if (status === 'FAIL') data.cell.styles.textColor = [200, 0, 0];
                        else if (status === 'WARNING') data.cell.styles.textColor = [200, 160, 0];
                        else data.cell.styles.textColor = [0, 150, 0];
                    }
                }
            });
        }

        // Save
        const filename = `Calculation_Book_${project.jobNo || 'Draft'}.pdf`;
        doc.save(filename);
    }
};
