"""Centralized defaults for layout_solver_v2.

These values are intentionally separated from solver logic to reduce hardcoding
and make policy/code tuning safer and traceable.
"""

# Site and zoning defaults
DEFAULT_SETBACK_FRONT_M = 3.0
DEFAULT_SETBACK_SIDE_M = 1.5
DEFAULT_FSI_LIMIT = 1.5
DEFAULT_SITE_NORTH_ANGLE_DEG = 0.0
DEFAULT_SITE_LATITUDE_DEG = 20.0
DEFAULT_NUM_FLOORS = 1

# Global constraints defaults
DEFAULT_MAX_UNSUPPORTED_SPAN_M = 5.0
DEFAULT_MIN_CEILING_HEIGHT_M = 3.0
DEFAULT_STRUCTURAL_GRID_MODULE_M = 0.5
DEFAULT_MAX_RISER_HEIGHT_M = 0.19
DEFAULT_MIN_TREAD_DEPTH_M = 0.25
DEFAULT_FLOOR_TO_FLOOR_HEIGHT_M = 3.0
DEFAULT_MAX_CIRCULATION_RATIO = 0.15
DEFAULT_MAX_EGRESS_DISTANCE_M = 22.0
DEFAULT_MIN_FENESTRATION_RATIO = 0.10
DEFAULT_DOOR_SWING_CLEARANCE_M = 0.9

# Geometry and tolerance defaults
DEFAULT_EDGE_TOL_M = 0.05
DEFAULT_RECT_ADJACENCY_TOL_M = 0.3
DEFAULT_MIN_CLEARANCE_FALLBACK_M = 2.0

# Fenestration defaults
DEFAULT_FENESTRATION_CEILING_HEIGHT_M = 3.0
DEFAULT_WINDOW_AREA_PER_SQM_DIVISOR = 10.0
DEFAULT_WWR_MAX = 0.60
DEFAULT_NBC_OPENABLE_RATIO = 0.125  # 1/8

# Solar/shading defaults
DEFAULT_BASE_OVERHANG_DEPTH_M = 0.6
DEFAULT_OVERHANG_DEPTH_FACTOR_M = 0.4
DEFAULT_SHADING_REDUCTION_FACTOR = 0.4
DEFAULT_SOLAR_HIGH_PENALTY_THRESHOLD = 0.5
DEFAULT_SOLAR_LATITUDE_REFERENCE_DEG = 23.5
DEFAULT_SOLAR_LATITUDE_DIVISOR = 50.0
DEFAULT_SOLAR_LATITUDE_MIN_FACTOR = 0.5

# Acoustic buffer defaults
DEFAULT_ACOUSTIC_BUFFER_WIDTH_M = 1.2
DEFAULT_ACOUSTIC_MIN_BUFFER_WIDTH_M = 0.6
DEFAULT_ACOUSTIC_ADJACENCY_TOL_M = 0.4
DEFAULT_BUFFER_ROOM_MIN_WIDTH_M = 0.6
DEFAULT_BUFFER_OVERLAP_MIN_M = 1.0
DEFAULT_BUFFER_MIN_AREA_SQM = 0.5
DEFAULT_BUFFER_ROOM_MAX_ASPECT_RATIO = 5.0

# Pathfinding/grid defaults
DEFAULT_FLOORGRID_CELL_SIZE_M = 0.2
DEFAULT_FLOORGRID_WALL_THICKNESS_M = 0.2

# Structural grid output defaults
DEFAULT_STRUCTURAL_OUTPUT_GRID_MODULE_M = 3.0
DEFAULT_STRUCTURAL_OUTPUT_MAX_SPAN_M = 5.0
DEFAULT_STRUCTURAL_OUTPUT_MAX_SPAN_REPORT_M = 6.0
DEFAULT_STRUCTURAL_GRID_DEDUP_FACTOR = 0.3
DEFAULT_STRUCTURAL_TRIVIAL_SPAN_M = 0.5

# Simulated annealing defaults
DEFAULT_SA_INITIAL_TEMP = 1000.0
DEFAULT_SA_COOLING_RATE = 0.995
DEFAULT_SA_MIN_TEMP = 0.1
DEFAULT_SA_MAX_ITERATIONS = 5000
DEFAULT_SA_STAGNATION_LIMIT = 50
DEFAULT_SA_RESIZE_DELTA = 0.15
DEFAULT_SA_NUDGE_FACTOR = 0.5

# Structural and circulation heuristics
DEFAULT_BEAM_DEPTH_DIVISOR = 10.0
DEFAULT_MIN_HEADROOM_UNDER_BEAM_M = 2.4
DEFAULT_PLUMBING_ADJ_WEIGHT = 5.0
DEFAULT_SOLVER_CONVERGENCE_TARGET = 1.0
DEFAULT_ADJUSTMENT_BLEND = 0.35

# Structural handoff and MEP thresholds
DEFAULT_WALL_SHARED_TOL_M = 0.05
DEFAULT_WALL_SHARED_MIN_OVERLAP_M = 0.1
DEFAULT_CANTILEVER_MIN_OVERHANG_M = 0.05
DEFAULT_SLAB_ONE_WAY_RATIO = 2.0
DEFAULT_MEP_STACK_PROXIMITY_M = 2.0
DEFAULT_LIGHTING_AREA_DIVISOR = 6
DEFAULT_HVAC_SPLIT_THRESHOLD_TR = 10.0

# Staircase defaults
DEFAULT_STAIR_WIDTH_M = 1.0
DEFAULT_STAIR_FLIGHT_GAP_M = 0.1
