import { describe, it, expect } from 'vitest';
import { BEAMLAB_COMPANY, BEAMLAB_COLORS } from '../BrandingConstants';

describe('C1 — BEAMLAB_COMPANY.name bug condition exploration', () => {
  it('BEAMLAB_COMPANY.name should be "BeamLab Ultimate" (will FAIL on unfixed code)', () => {
    expect(BEAMLAB_COMPANY.name).toBe('BeamLab Ultimate');
  });
});

describe('P4 — BEAMLAB_COMPANY preservation: other fields unchanged', () => {
  it('tagline is unchanged', () => {
    expect(BEAMLAB_COMPANY.tagline).toBe('Structural Engineering');
  });
  it('website is unchanged', () => {
    expect(BEAMLAB_COMPANY.website).toBe('beamlabultimate.tech');
  });
  it('email is unchanged', () => {
    expect(BEAMLAB_COMPANY.email).toBe('office@beamlabultimate.tech');
  });
  it('generatedByLine is unchanged', () => {
    expect(BEAMLAB_COMPANY.generatedByLine).toBe(
      'Generated by BeamLab Ultimate — Professional Structural Engineering Software'
    );
  });
  it('disclaimer is unchanged', () => {
    expect(BEAMLAB_COMPANY.disclaimer).toBe(
      'Not for construction without independent verification.'
    );
  });
});

describe('P4 — BEAMLAB_COLORS preservation', () => {
  it('navy color is unchanged', () => {
    expect(BEAMLAB_COLORS.navy).toBe('#12376A');
  });
  it('gold color is unchanged', () => {
    expect(BEAMLAB_COLORS.gold).toBe('#BF9B30');
  });
  it('royalBlue color is unchanged', () => {
    expect(BEAMLAB_COLORS.royalBlue).toBe('#1D4ED8');
  });
});
