import { ProjectInfo } from "../../store/model";

/**
 * ReportGeneratorService.ts
 * 
 * Generates professional reports for Multi-Disciplinary Civil Engineering projects.
 * Outputs: Markdown (which can be rendered to PDF)
 */

interface ReportSection {
    title: string;
    content: string;
}

export const ReportGeneratorService = {

    /**
     * Generate a full project report
     */
    generateProjectReport(projectInfo: ProjectInfo, modulesData: Record<string, any>): string {
        const dateStr = new Date().toLocaleDateString();

        let report = `# ENGINEERING DESIGN REPORT\n\n`;

        // 1. Project Header
        report += `**Project:** ${projectInfo.name}\n`;
        report += `**Client:** ${projectInfo.client}\n`;
        report += `**Engineer:** ${projectInfo.engineer}\n`;
        report += `**Date:** ${dateStr}\n`;
        report += `**Job No:** ${projectInfo.jobNo}\n`;
        report += `---\n\n`;

        // 2. Executive Summary
        report += `## 1. Executive Summary\n`;
        report += `This report details the design and analysis performed for the above project. `;
        report += `It includes the following disciplines:\n\n`;

        if (modulesData.geotech) report += `- Geotechnical Engineering\n`;
        if (modulesData.transport) report += `- Transportation Engineering\n`;
        if (modulesData.hydraulics) report += `- Hydraulics & Hydrology\n`;
        if (modulesData.structural) report += `- Structural Engineering\n`;

        report += `\n---\n\n`;

        // 3. Geotechnical Section
        if (modulesData.geotech && modulesData.geotech.results) {
            report += `## 2. Geotechnical Analysis\n\n`;

            modulesData.geotech.results.forEach((res: any, idx: number) => {
                report += `### 2.${idx + 1} Foundation Design (ID: ${res.id || idx + 1})\n`;
                report += `**Inputs:**\n`;
                report += `- Type: Speed Footing\n`;
                report += `- Dimensions: ${res.input.width}m x ${res.input.length}m\n`;
                report += `- Soil Cohesion: ${res.input.cohesion} kPa\n`;
                report += `- Friction Angle: ${res.input.frictionAngle}°\n\n`;

                report += `**Results:**\n`;
                report += `> **Allowable Bearing Capacity:** ${res.output.qall.toFixed(2)} kPa\n`;
                report += `> **Factor of Safety:** ${res.output.factorOfSafety}\n`;
                report += `> **Failure Mode:** ${res.output.failureMode}\n\n`;
            });
        }

        // 4. Transportation Section
        if (modulesData.transport && modulesData.transport.results) {
            report += `## 3. Transportation Design\n\n`;

            modulesData.transport.results.forEach((res: any, idx: number) => {
                report += `### 3.${idx + 1} Horizontal Curve Design\n`;
                report += `- Design Speed: ${res.input.speed} km/h\n`;
                report += `- Deflection Angle: ${res.input.angle}°\n`;
                report += `- Calculated Radius: **${res.output.radius.toFixed(2)} m**\n`;
                report += `- Transition Length: **${res.output.transitionLength.toFixed(2)} m**\n`;
                report += `- Superelevation: ${res.output.superelevation}%\n\n`;
            });
        }

        // 5. Hydraulics Section
        if (modulesData.hydraulics && modulesData.hydraulics.results) {
            report += `## 4. Hydraulics Analysis\n\n`;

            modulesData.hydraulics.results.forEach((res: any, idx: number) => {
                report += `### 4.${idx + 1} Open Channel Flow\n`;
                report += `- Channel Type: ${res.input.type}\n`;
                report += `- Dimensions: ${res.input.baseWidth}m Width\n`;
                report += `- Calculated Discharge: **${res.output.discharge.toFixed(3)} m³/s**\n`;
                report += `- Velocity: ${res.output.velocity.toFixed(2)} m/s\n`;
                report += `- Froude Number: ${res.output.froudeNumber.toFixed(2)} (${res.output.flowRegime})\n\n`;
            });
        }

        report += `\n---\n`;
        report += `*Generated by AI Architect | BeamLab Pro*\n`;

        return report;
    }
};
