/**
 * contracts/schema.ts — Schema versioning & canonical entity ID contracts.
 *
 * Every payload between frontend → Node API → Rust/Python follows:
 *   1. A monotonic schema_version integer.
 *   2. Canonical string IDs for all entities.
 *   3. A migration strategy from v(N) → v(N+1).
 */

// ─── Schema Version ─────────────────────────────────────────────────────────

/** Current payload schema version.  Bump whenever the JSON shape changes. */
export const SCHEMA_VERSION = 2;

/**
 * Schema version history:
 *   v1 — Original: nodes/members/loads/supports/loadCases/loadCombinations
 *   v2 — Added propertyAssignments[], floorLoads[], plates[], seismicProfile, windProfile
 */

/** Attach to every outgoing analysis payload. */
export interface VersionedPayload {
  schema_version: number;
}

// ─── Entity ID Contracts ────────────────────────────────────────────────────

/**
 * All entity IDs are opaque strings.  The ONLY requirement is uniqueness
 * within the entity's own collection.  Cross-references use the string
 * ID verbatim — never a numeric index.
 *
 * Naming convention (generated by store):
 *   Node:         "N1", "N2", …
 *   Member:       "M1", "M2", …
 *   Plate:        "P1", "P2", …
 *   Load Case:    "LC_dead", "LC_live", "LC_wind", "LC_seismic", …
 *   Load Combo:   "COMB_1", "COMB_2", …
 *   Property:     "PROP_1", "PROP_2", …
 *   Material:     "MAT_1", "MAT_2", …
 *   Group:        "GRP_frame1", "GRP_bracing", …
 */
export type NodeId = string;
export type MemberId = string;
export type PlateId = string;
export type LoadCaseId = string;
export type LoadCombinationId = string;
export type PropertyId = string;
export type MaterialId = string;
export type GroupId = string;

// ─── Reference Integrity ────────────────────────────────────────────────────

/**
 * Cross-reference rules enforced at the Zod validation boundary:
 *
 *   1. Member.startNodeId and Member.endNodeId must exist in nodes[].
 *   2. Member.startNodeId ≠ Member.endNodeId (zero-length member).
 *   3. PropertyAssignment.assignment.memberIds must be a subset of members[].id.
 *   4. PropertyAssignment.assignment.groupIds must be a subset of groups[].id (when defined).
 *   5. Load.nodeId must exist in nodes[].
 *   6. MemberLoad.memberId must exist in members[].
 *   7. LoadCombination.factors[].loadCaseId must exist in loadCases[].
 *   8. Plate.nodeIds must all exist in nodes[] and must be unique.
 *   9. FloorLoad.loadCase must exist in loadCases[] (when strict mode is on).
 */

// ─── Migration ──────────────────────────────────────────────────────────────

/**
 * Migrate a saved-project payload from any older version to SCHEMA_VERSION.
 * Each step is additive — it fills new optional fields with safe defaults.
 */
export function migratePayload<T extends Record<string, unknown>>(raw: T): T & VersionedPayload {
  const version = (raw.schema_version as number) ?? 1;
  const out = { ...raw } as T & VersionedPayload;

  if (version < 2) {
    // v1 → v2: add missing collection arrays
    if (!('propertyAssignments' in out)) (out as Record<string, unknown>).propertyAssignments = [];
    if (!('floorLoads' in out)) (out as Record<string, unknown>).floorLoads = [];
    if (!('plates' in out)) (out as Record<string, unknown>).plates = [];
  }

  out.schema_version = SCHEMA_VERSION;
  return out;
}

// ─── Validation Boundaries ──────────────────────────────────────────────────

/**
 * Three-layer validation architecture:
 *
 *   Layer 1 — Frontend (Zustand store)
 *     • Type-level guarantees via TypeScript interfaces.
 *     • Pre-flight checks before API call (non-empty nodes, non-zero E, etc.).
 *     • UI-level feedback (red borders, toast messages).
 *
 *   Layer 2 — Node API Gateway (Zod schemas, validation.ts)
 *     • Runtime JSON validation for every POST body.
 *     • Cross-reference integrity (member refs valid nodes).
 *     • Bounds enforcement (0 < E, 0 < A, 0 ≤ factor ≤ 100).
 *     • Wind + EQ mutual-exclusion per IS 1893 Cl. 6.3.2.
 *     • Returns structured 400 errors with field paths.
 *
 *   Layer 3 — Rust/Python Backends (typed structs)
 *     • Serde deserialization into strongly-typed structs.
 *     • No loose `serde_json::Value` in hot paths.
 *     • Solver returns `Result<T, SolverError>` — never panics.
 */
export const VALIDATION_LIMITS = {
  MAX_NODES: 50_000,
  MAX_MEMBERS: 100_000,
  MAX_LOADS: 100_000,
  MAX_PROPERTY_ASSIGNMENTS: 100_000,
  MAX_LOAD_CASES: 500,
  MAX_LOAD_COMBINATIONS: 5_000,
  MAX_PLATES: 50_000,
  MAX_FLOOR_LOADS: 10_000,
  MIN_ELASTIC_MODULUS_KN_M2: 1,       // 1 kN/m² (rubber-like)
  MAX_ELASTIC_MODULUS_KN_M2: 1e12,    // 1e12 kN/m² (diamond)
  MIN_AREA_M2: 1e-10,
  MAX_AREA_M2: 100,
} as const;
