/**
 * BrandingConstants.ts
 *
 * Single source of truth for BeamLab brand identity.
 * Used by all report templates, export services, and UI components.
 * Update here → changes propagate everywhere.
 */

// ─── Brand Colors ──────────────────────────────────────────────────────────

export const BEAMLAB_COLORS = {
  /** Primary navy — used for headers, accent bars, titles */
  navy: '#12376A',
  /** Royal blue — used for interactive elements and links */
  royalBlue: '#1D4ED8',
  /** Gold — used for accent stripe under header bar */
  gold: '#BF9B30',
  /** White — primary background for reports */
  white: '#FFFFFF',
  /** Slate 50 — alternate row / card background */
  slate50: '#F8FAFC',
  /** Slate 100 — table header background */
  slate100: '#F1F5F9',
  /** Slate 200 — borders, dividers */
  slate200: '#E2E8F0',
  /** Slate 300 — heavier borders */
  slate300: '#CBD5E1',
  /** Slate 500 — secondary labels */
  slate500: '#64748B',
  /** Slate 600 — body text secondary */
  slate600: '#475569',
  /** Slate 700 — body text */
  slate700: '#334155',
  /** Slate 900 — primary text */
  slate900: '#0F172A',
  /** Green — pass status */
  green: '#16A34A',
  /** Green bg — pass status background */
  greenBg: '#DCFCE7',
  /** Red — fail status */
  red: '#DC2626',
  /** Red bg — fail status background */
  redBg: '#FEE2E2',
  /** Amber — warning status */
  amber: '#D97706',
  /** Amber bg — warning background */
  amberBg: '#FEF3C7',
} as const;

/** jsPDF-compatible RGB tuples (0–255) — derived from hex above */
export const BEAMLAB_COLORS_RGB = {
  navy:      [18,  55, 106] as [number, number, number],
  gold:      [191, 155, 48] as [number, number, number],
  white:     [255, 255, 255] as [number, number, number],
  slate50:   [248, 250, 252] as [number, number, number],
  slate100:  [241, 245, 249] as [number, number, number],
  slate200:  [226, 232, 240] as [number, number, number],
  slate500:  [100, 116, 139] as [number, number, number],
  slate600:  [71,  85, 105] as [number, number, number],
  slate700:  [51,  65,  85] as [number, number, number],
  slate900:  [15,  23,  42] as [number, number, number],
  green:     [22, 163, 74] as [number, number, number],
  red:       [220,  38,  38] as [number, number, number],
  amber:     [217, 119,   6] as [number, number, number],
} as const;

// ─── Company Info ──────────────────────────────────────────────────────────

export const BEAMLAB_COMPANY = {
  name: 'BeamLab',
  tagline: 'Structural Engineering',
  website: 'beamlabultimate.tech',
  email: 'office@beamlabultimate.tech',
  disclaimer: 'Not for construction without independent verification.',
  generatedByLine: 'Generated by BeamLab Ultimate — Professional Structural Engineering Software',
} as const;

// ─── Logo Paths ────────────────────────────────────────────────────────────

export const BEAMLAB_LOGO = {
  /** Primary colored SVG icon — works on white/light backgrounds */
  iconColored: '/branding/beamlab_icon_colored.svg',
  /** Dark monochrome icon — for light backgrounds without color */
  iconDark: '/branding/beamlab_icon_dark.svg',
  /** White icon — for dark/navy backgrounds */
  iconWhite: '/branding/beamlab_icon_white.svg',
  /** Full wordmark SVG */
  wordmark: '/branding/beamlab_wordmark.svg',
} as const;

// ─── Report Accent Bar Style (CSS-in-JS) ───────────────────────────────────

/** Top navy accent bar — absolute position, top:0, full-width, 6px high */
export const REPORT_ACCENT_TOP_CSS = `
  position: absolute; top: 0; left: 0; right: 0;
  height: 6px; background: ${BEAMLAB_COLORS.navy};
` as const;

/** Gold stripe immediately below navy bar — 3px high */
export const REPORT_ACCENT_GOLD_CSS = `
  position: absolute; top: 6px; left: 0; right: 0;
  height: 3px; background: ${BEAMLAB_COLORS.gold};
` as const;

// ─── Typography ────────────────────────────────────────────────────────────

export const REPORT_FONT_STACK =
  "'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif";

export const REPORT_MONO_STACK =
  "'SF Mono', 'Cascadia Code', 'Consolas', monospace";

// ─── Page / Print Settings ─────────────────────────────────────────────────

export const REPORT_PAGE = {
  size: 'A4',
  maxWidth: '210mm',
  margins: { top: 20, right: 15, bottom: 25, left: 15 }, // mm
} as const;
