#!/usr/bin/env python3

"""
BeamLab Configuration Manager
Manages environment setup for local and Azure deployment
"""

import os
import sys
import json
import argparse
from pathlib import Path
from typing import Dict, Optional
import subprocess

class BeamLabConfig:
    """Manages BeamLab environment configuration"""
    
    # Required settings for all environments
    REQUIRED_SETTINGS = {
        'GEMINI_API_KEY': 'Google AI/Gemini API Key',
        'USE_MOCK_AI': 'Use mock AI (true/false)',
        'FRONTEND_URL': 'Frontend URL',
        'ALLOWED_ORIGINS': 'Comma-separated allowed origins',
    }
    
    # Default values for local development
    LOCAL_DEFAULTS = {
        'GEMINI_API_KEY': 'local-dev-key-not-set',
        'USE_MOCK_AI': 'true',
        'FRONTEND_URL': 'http://localhost:5173',
        'ALLOWED_ORIGINS': 'http://localhost:5173,http://localhost:3001,http://localhost:8000,http://127.0.0.1:5173',
    }
    
    # Default values for production
    PRODUCTION_DEFAULTS = {
        'GEMINI_API_KEY': 'must-be-set',
        'USE_MOCK_AI': 'false',
        'FRONTEND_URL': 'https://beamlabultimate.tech',
        'ALLOWED_ORIGINS': 'https://beamlabultimate.tech,https://www.beamlabultimate.tech,https://brave-mushroom-0eae8ec00.4.azurestaticapps.net',
    }
    
    def __init__(self, workspace_root: Optional[str] = None):
        """Initialize config manager"""
        self.workspace_root = Path(workspace_root or os.getcwd())
        self.env_file = self.workspace_root / '.env'
        self.env_example = self.workspace_root / '.env.example'
        
    def load_env(self) -> Dict[str, str]:
        """Load environment from .env file"""
        env_vars = {}
        if self.env_file.exists():
            with open(self.env_file) as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#'):
                        if '=' in line:
                            key, value = line.split('=', 1)
                            env_vars[key.strip()] = value.strip().strip('"').strip("'")
        return env_vars
    
    def save_env(self, config: Dict[str, str]) -> None:
        """Save environment to .env file"""
        with open(self.env_file, 'w') as f:
            f.write("# BeamLab Configuration\n")
            f.write("# Auto-generated by config manager\n\n")
            for key in sorted(self.REQUIRED_SETTINGS.keys()):
                value = config.get(key, '')
                # Mask API keys in output
                display_value = '[REDACTED]' if 'KEY' in key and value else value
                f.write(f"{key}={value}\n")
        print(f"✓ Configuration saved to {self.env_file}")
    
    def validate_config(self, config: Dict[str, str], environment: str = 'local') -> bool:
        """Validate required settings"""
        valid = True
        for key in self.REQUIRED_SETTINGS.keys():
            value = config.get(key, '').strip()
            
            if not value or value == 'not-set' or value == 'must-be-set':
                print(f"❌ {key}: Not configured")
                valid = False
            else:
                display_value = '[REDACTED]' if 'KEY' in key else value
                print(f"✓ {key}: {display_value}")
        
        return valid
    
    def setup_local(self, interactive: bool = True) -> Dict[str, str]:
        """Setup local development environment"""
        print("\n" + "="*60)
        print("  BeamLab Local Development Setup")
        print("="*60)
        
        config = self.LOCAL_DEFAULTS.copy()
        
        if interactive:
            print("\nEnter configuration values (press Enter for defaults):\n")
            
            for key in self.REQUIRED_SETTINGS.keys():
                prompt = f"{key} [{config[key][:30]}{'...' if len(config[key]) > 30 else ''}]: "
                value = input(prompt).strip()
                if value:
                    config[key] = value
        
        print("\nConfiguration Summary:")
        self.validate_config(config, 'local')
        
        self.save_env(config)
        return config
    
    def setup_azure(self, resource_group: str, app_name: str, gemini_key: str, dry_run: bool = False) -> bool:
        """Setup Azure App Service environment"""
        print("\n" + "="*60)
        print("  BeamLab Azure Setup")
        print("="*60)
        print(f"\nResource Group: {resource_group}")
        print(f"App Name: {app_name}")
        
        config = self.PRODUCTION_DEFAULTS.copy()
        config['GEMINI_API_KEY'] = gemini_key
        
        print("\nSettings to apply:")
        for key, value in config.items():
            display = '[REDACTED]' if 'KEY' in key else value
            print(f"  • {key}: {display}")
        
        if dry_run:
            print("\n[DRY-RUN] No changes will be made.")
            return True
        
        # Confirm
        if input("\nContinue? (yes/no): ").lower() != 'yes':
            print("Cancelled.")
            return False
        
        # Run az command
        settings_str = ' '.join([f"{k}=\"{v}\"" for k, v in config.items()])
        cmd = f"az webapp config appsettings set -g {resource_group} -n {app_name} --settings {settings_str}"
        
        try:
            subprocess.run(cmd, shell=True, check=True)
            print("✓ Settings applied")
            
            # Restart
            subprocess.run(
                f"az webapp restart -g {resource_group} -n {app_name}",
                shell=True,
                check=True
            )
            print("✓ App restarted")
            
            return True
        except subprocess.CalledProcessError as e:
            print(f"❌ Error: {e}")
            return False
    
    def verify_azure(self, resource_group: str, app_name: str) -> None:
        """Verify Azure settings"""
        cmd = (
            f"az webapp config appsettings list "
            f"-g {resource_group} -n {app_name} "
            f"--query \"[?name=='GEMINI_API_KEY' || name=='USE_MOCK_AI' || "
            f"name=='FRONTEND_URL' || name=='ALLOWED_ORIGINS']\""
        )
        
        try:
            result = subprocess.run(cmd, shell=True, capture_output=True, text=True, check=True)
            print("\nCurrent Azure Settings:")
            print(result.stdout)
        except subprocess.CalledProcessError as e:
            print(f"❌ Failed to verify: {e}")


def main():
    parser = argparse.ArgumentParser(
        description='BeamLab Configuration Manager',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Interactive local setup
  python config_manager.py local
  
  # Setup Azure (replace with your values)
  python config_manager.py azure \
    --resource-group beamlab-ci-rg \
    --app-name beamlab-backend-python \
    --api-key AIza_YOUR_KEY
  
  # Dry-run Azure setup
  python config_manager.py azure \
    --resource-group beamlab-ci-rg \
    --app-name beamlab-backend-python \
    --api-key AIza_YOUR_KEY \
    --dry-run
  
  # Verify Azure settings
  python config_manager.py verify-azure \
    --resource-group beamlab-ci-rg \
    --app-name beamlab-backend-python
        """
    )
    
    subparsers = parser.add_subparsers(dest='command', help='Command to run')
    
    # Local setup
    local_parser = subparsers.add_parser('local', help='Setup local development')
    local_parser.add_argument('--no-interactive', action='store_true', help='Use defaults without prompting')
    
    # Azure setup
    azure_parser = subparsers.add_parser('azure', help='Setup Azure App Service')
    azure_parser.add_argument('--resource-group', required=True, help='Azure resource group')
    azure_parser.add_argument('--app-name', required=True, help='Azure app service name')
    azure_parser.add_argument('--api-key', required=True, help='Gemini API key')
    azure_parser.add_argument('--dry-run', action='store_true', help='Show what would be done without making changes')
    
    # Verify Azure
    verify_parser = subparsers.add_parser('verify-azure', help='Verify Azure settings')
    verify_parser.add_argument('--resource-group', required=True, help='Azure resource group')
    verify_parser.add_argument('--app-name', required=True, help='Azure app service name')
    
    args = parser.parse_args()
    
    config = BeamLabConfig()
    
    if args.command == 'local':
        config.setup_local(interactive=not args.no_interactive)
    elif args.command == 'azure':
        success = config.setup_azure(
            args.resource_group,
            args.app_name,
            args.api_key,
            dry_run=args.dry_run
        )
        sys.exit(0 if success else 1)
    elif args.command == 'verify-azure':
        config.verify_azure(args.resource_group, args.app_name)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == '__main__':
    main()
