// jsPDF + autoTable loaded on-demand (~250KB) — only fetched when user generates a report
let _jspdfMod: typeof import('jspdf') | null = null;
let _autoTableMod: typeof import('jspdf-autotable') | null = null;
async function loadPdfLibs() {
  if (!_jspdfMod || !_autoTableMod) {
    [_jspdfMod, _autoTableMod] = await Promise.all([
      import('jspdf'),
      import('jspdf-autotable'),
    ]);
  }
  return { jsPDF: _jspdfMod.jsPDF, autoTable: _autoTableMod.default };
}
import { useModelStore, type AnalysisResults } from '../store/model';
import { LOGO_BASE64 } from './LogoData';

// ============================================
// REPORT GENERATOR
// ============================================
// Generates professional PDF reports for structural analysis

export interface ReportConfig {
    projectName?: string;
    projectNumber?: string;
    engineer?: string;
    company?: string;
    isProUser?: boolean;  // Pro users get clean PDFs, free users get watermark
    includeScreenshot?: boolean;
    includeSummary?: boolean;
    includeDisplacements?: boolean;
    includeReactions?: boolean;
    includeMemberForces?: boolean;
}

const DEFAULT_CONFIG: ReportConfig = {
    projectName: 'Structural Analysis',
    projectNumber: '',
    engineer: '',
    company: 'BeamLab',
    isProUser: false,  // Default to free tier (with watermark)
    includeScreenshot: true,
    includeSummary: true,
    includeDisplacements: true,
    includeReactions: true,
    includeMemberForces: true
};

// Format number to 3 decimal places
const fmt = (val: number): string => val.toFixed(3);

// Format date
const formatDate = (): string => {
    return new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    });
};

export class ReportGenerator {
    private doc: any;
    private pageWidth: number;
    private pageHeight: number;
    private margin: number = 20;
    private currentY: number = 20;
    private config: ReportConfig;
    private autoTable: any;

    private constructor(config: ReportConfig, doc: any, autoTable: any) {
        this.config = config;
        this.doc = doc;
        this.autoTable = autoTable;
        this.pageWidth = this.doc.internal.pageSize.getWidth();
        this.pageHeight = this.doc.internal.pageSize.getHeight();
    }

    static async create(config: Partial<ReportConfig> = {}): Promise<ReportGenerator> {
        const { jsPDF, autoTable } = await loadPdfLibs();
        const doc = new jsPDF('p', 'mm', 'a4');
        return new ReportGenerator({ ...DEFAULT_CONFIG, ...config }, doc, autoTable);
    }

    /**
     * Capture the 3D canvas as a data URL
     */
    static captureCanvas(canvas: HTMLCanvasElement | null): string | null {
        if (!canvas) return null;
        try {
            return canvas.toDataURL('image/png', 1.0);
        } catch (e) {
            console.error('Failed to capture canvas:', e);
            return null;
        }
    }

    /**
     * Add header section with company info and project details
     */
    private addHeader(): void {
        const { projectName, projectNumber, company, engineer } = this.config;

        // Title bar - BeamLab branding
        this.doc.setFillColor(30, 58, 138); // Dark blue
        this.doc.rect(0, 0, this.pageWidth, 35, 'F'); // Increased height for logo

        // Logo
        try {
            // Add logo at top left
            this.doc.addImage(LOGO_BASE64, 'PNG', this.margin, 5, 20, 20);
        } catch (e) {
            console.error("Could not add logo to PDF", e);
        }

        // Company name
        this.doc.setTextColor(255, 255, 255);
        this.doc.setFontSize(22);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text('BeamLab', this.margin + 25, 18);

        this.doc.setFontSize(10);
        this.doc.setFont('helvetica', 'normal');
        this.doc.text('Structural Analysis Platform', this.margin + 25, 25);

        // Report title on right
        this.doc.setFontSize(14);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text('STRUCTURAL CALCULATION REPORT', this.pageWidth - this.margin, 15, { align: 'right' });

        this.doc.setFontSize(9);
        this.doc.setFont('helvetica', 'normal');
        this.doc.text('Generated by beamlab.app', this.pageWidth - this.margin, 22, { align: 'right' });

        // Timestamp
        const timestamp = new Date().toLocaleString();
        this.doc.text(`Generated: ${timestamp}`, this.pageWidth - this.margin, 28, { align: 'right' });

        this.currentY = 45;

        // Project info box
        this.doc.setDrawColor(200, 200, 200);
        this.doc.setFillColor(250, 250, 250);
        this.doc.roundedRect(this.margin, this.currentY, this.pageWidth - 2 * this.margin, 35, 2, 2, 'FD');

        this.doc.setTextColor(0, 0, 0);
        this.doc.setFontSize(10);

        const col1X = this.margin + 5;
        const col2X = this.pageWidth / 2 + 5;
        const rowHeight = 8;
        const startTextY = this.currentY + 10;

        // Left Column
        this.doc.setFont('helvetica', 'bold');
        this.doc.text('Project Name:', col1X, startTextY);
        this.doc.setFont('helvetica', 'normal');
        this.doc.text(projectName || 'Untitled Project', col1X + 35, startTextY);

        this.doc.setFont('helvetica', 'bold');
        this.doc.text('Project No:', col1X, startTextY + rowHeight);
        this.doc.setFont('helvetica', 'normal');
        this.doc.text(projectNumber || 'N/A', col1X + 35, startTextY + rowHeight);

        this.doc.setFont('helvetica', 'bold');
        this.doc.text('Client:', col1X, startTextY + rowHeight * 2);
        this.doc.setFont('helvetica', 'normal');
        this.doc.text(company || 'N/A', col1X + 35, startTextY + rowHeight * 2);

        // Right Column
        this.doc.setFont('helvetica', 'bold');
        this.doc.text('Engineer:', col2X, startTextY);
        this.doc.setFont('helvetica', 'normal');
        this.doc.text(engineer || 'N/A', col2X + 25, startTextY);

        this.doc.setFont('helvetica', 'bold');
        this.doc.text('Design Code:', col2X, startTextY + rowHeight);
        this.doc.setFont('helvetica', 'normal');
        this.doc.text('IS 800:2007', col2X + 25, startTextY + rowHeight);

        this.doc.setFont('helvetica', 'bold');
        this.doc.text('Checked By:', col2X, startTextY + rowHeight * 2);
        this.doc.setFont('helvetica', 'normal');
        this.doc.text('_________________', col2X + 25, startTextY + rowHeight * 2);

        this.currentY += 45;
    }

    /**
     * Add section title
     */
    private addSectionTitle(title: string): void {
        if (this.currentY > this.pageHeight - 40) {
            this.doc.addPage();
            this.currentY = 20;
        }

        this.doc.setFillColor(241, 245, 249); // Light gray
        this.doc.rect(this.margin, this.currentY - 5, this.pageWidth - 2 * this.margin, 10, 'F');

        this.doc.setTextColor(30, 58, 138);
        this.doc.setFontSize(12);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text(title, this.margin + 3, this.currentY + 2);

        this.currentY += 12;
        this.doc.setTextColor(0, 0, 0);
        this.doc.setFont('helvetica', 'normal');
    }

    /**
     * Add model statistics section
     */
    private addModelStatistics(): void {
        const state = useModelStore.getState();
        const nodeCount = state.nodes.size;
        const memberCount = state.members.size;
        const loadCount = state.loads.length;

        // Count supports
        let supportCount = 0;
        for (const node of state.nodes.values()) {
            if (node.restraints && (node.restraints.fx || node.restraints.fy || node.restraints.mz)) {
                supportCount++;
            }
        }

        this.addSectionTitle('1. Model Summary');

        const statsData = [
            ['Total Nodes', nodeCount.toString()],
            ['Total Members', memberCount.toString()],
            ['Support Points', supportCount.toString()],
            ['Applied Loads', loadCount.toString()]
        ];

        this.autoTable(this.doc, {
            startY: this.currentY,
            head: [['Property', 'Value']],
            body: statsData,
            margin: { left: this.margin, right: this.margin },
            styles: { fontSize: 9 },
            headStyles: { fillColor: [30, 58, 138] },
            alternateRowStyles: { fillColor: [248, 250, 252] }
        });

        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        this.currentY = (this.doc as any).lastAutoTable.finalY + 10;
    }

    /**
     * Add load cases section
     */
    private addLoadCases(): void {
        const state = useModelStore.getState();

        if (state.loads.length === 0) return;

        this.addSectionTitle('2. Applied Loads');

        const loadData = state.loads.map((load, i) => [
            `L${i + 1}`,
            load.nodeId.substring(0, 8) + '...',
            fmt(load.fx ?? 0),
            fmt(load.fy ?? 0),
            fmt(load.fz ?? 0),
            fmt(load.mx ?? 0),
            fmt(load.my ?? 0),
            fmt(load.mz ?? 0)
        ]);

        this.autoTable(this.doc, {
            startY: this.currentY,
            head: [['ID', 'Node', 'Fx (kN)', 'Fy (kN)', 'Fz (kN)', 'Mx (kN·m)', 'My (kN·m)', 'Mz (kN·m)']],
            body: loadData,
            margin: { left: this.margin, right: this.margin },
            styles: { fontSize: 8 },
            headStyles: { fillColor: [30, 58, 138] },
            alternateRowStyles: { fillColor: [248, 250, 252] }
        });

        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        this.currentY = (this.doc as any).lastAutoTable.finalY + 10;
    }

    /**
     * Add reaction summary section
     */
    private addReactionSummary(results: AnalysisResults): void {
        const state = useModelStore.getState();

        this.addSectionTitle('3. Support Reactions');

        const reactionData: string[][] = [];

        for (const [nodeId, reaction] of results.reactions.entries()) {
            const node = state.nodes.get(nodeId);
            if (node?.restraints && (node.restraints.fx || node.restraints.fy || node.restraints.mz)) {
                reactionData.push([
                    nodeId.substring(0, 8) + '...',
                    fmt(reaction.fx),
                    fmt(reaction.fy),
                    fmt(reaction.fz),
                    fmt(reaction.mx),
                    fmt(reaction.my),
                    fmt(reaction.mz)
                ]);
            }
        }

        if (reactionData.length === 0) {
            this.doc.setFontSize(9);
            this.doc.text('No reactions available.', this.margin, this.currentY);
            this.currentY += 10;
            return;
        }

        this.autoTable(this.doc, {
            startY: this.currentY,
            head: [['Node', 'Rx (kN)', 'Ry (kN)', 'Rz (kN)', 'Mx (kN·m)', 'My (kN·m)', 'Mz (kN·m)']],
            body: reactionData,
            margin: { left: this.margin, right: this.margin },
            styles: { fontSize: 8 },
            headStyles: { fillColor: [30, 58, 138] },
            alternateRowStyles: { fillColor: [248, 250, 252] }
        });

        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        this.currentY = (this.doc as any).lastAutoTable.finalY + 10;
    }

    /**
     * Add member forces section
     */
    private addMemberForces(results: AnalysisResults): void {
        if (!this.config.includeMemberForces) return;

        this.addSectionTitle('4. Member Forces');

        const forceData: string[][] = [];

        for (const [memberId, forces] of results.memberForces.entries()) {
            forceData.push([
                memberId.substring(0, 8) + '...',
                fmt(forces.axial),
                fmt(forces.shearY),
                fmt(forces.shearZ),
                fmt(forces.momentY),
                fmt(forces.momentZ),
                fmt(forces.torsion)
            ]);
        }

        if (forceData.length === 0) {
            this.doc.setFontSize(9);
            this.doc.text('No member forces available.', this.margin, this.currentY);
            this.currentY += 10;
            return;
        }

        this.autoTable(this.doc, {
            startY: this.currentY,
            head: [['Member', 'N (kN)', 'Vy (kN)', 'Vz (kN)', 'My (kN·m)', 'Mz (kN·m)', 'T (kN·m)']],
            body: forceData,
            margin: { left: this.margin, right: this.margin },
            styles: { fontSize: 8 },
            headStyles: { fillColor: [30, 58, 138] },
            alternateRowStyles: { fillColor: [248, 250, 252] }
        });

        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        this.currentY = (this.doc as any).lastAutoTable.finalY + 10;
    }

    /**
     * Add 3D view screenshot
     */
    private addScreenshot(imageData: string): void {
        this.addSectionTitle('5. 3D Model View');

        // Check if we need a new page
        if (this.currentY > this.pageHeight - 100) {
            this.doc.addPage();
            this.currentY = 20;
        }

        const imgWidth = this.pageWidth - 2 * this.margin;
        const imgHeight = imgWidth * 0.6; // 16:10 aspect ratio

        this.doc.addImage(imageData, 'PNG', this.margin, this.currentY, imgWidth, imgHeight);
        this.currentY += imgHeight + 10;
    }

    /**
     * Add footer to all pages
     */
    private addFooter(): void {
        const pageCount = this.doc.getNumberOfPages();
        const year = new Date().getFullYear();

        for (let i = 1; i <= pageCount; i++) {
            this.doc.setPage(i);

            // Footer line
            this.doc.setDrawColor(200, 200, 200);
            this.doc.line(this.margin, this.pageHeight - 18, this.pageWidth - this.margin, this.pageHeight - 18);

            // Footer text - Copyright and branding
            this.doc.setFontSize(8);
            this.doc.setTextColor(128, 128, 128);
            this.doc.text(
                `© ${year} BeamLab | beamlab.app`,
                this.margin,
                this.pageHeight - 12
            );
            this.doc.text(
                `Page ${i} of ${pageCount}`,
                this.pageWidth - this.margin,
                this.pageHeight - 12,
                { align: 'right' }
            );
        }
    }

    /**
     * Generate the complete PDF report
     */
    generateReport(canvasScreenshot?: string | null): void {
        const state = useModelStore.getState();
        const results = state.analysisResults;

        // Header
        this.addHeader();

        // Model statistics
        if (this.config.includeSummary) {
            this.addModelStatistics();
        }

        // Load cases
        this.addLoadCases();

        // Analysis results
        if (results) {
            if (this.config.includeReactions) {
                this.addReactionSummary(results);
            }
            if (this.config.includeMemberForces) {
                this.addMemberForces(results);
            }
        } else {
            this.doc.setFontSize(10);
            this.doc.setTextColor(200, 100, 100);
            this.doc.text('Note: Analysis has not been run. Run analysis to include results.', this.margin, this.currentY);
            this.currentY += 15;
        }

        // Screenshot
        if (this.config.includeScreenshot && canvasScreenshot) {
            this.addScreenshot(canvasScreenshot);
        }

        // Add watermark for free tier users
        if (!this.config.isProUser) {
            this.addWatermark();
        }

        // Add footer to all pages
        this.addFooter();

        // Save the PDF with proper BeamLab filename
        const cleanName = this.config.projectName?.replace(/\s+/g, '_') || 'Structural_Analysis';
        const timestamp = new Date().toISOString().split('T')[0]; // YYYY-MM-DD
        const filename = `BeamLab_${cleanName}_${timestamp}.pdf`;
        this.doc.save(filename);
    }

    /**
     * Add FREE TRIAL watermark diagonal across all pages (for free tier)
     */
    private addWatermark(): void {
        const pageCount = this.doc.getNumberOfPages();

        for (let i = 1; i <= pageCount; i++) {
            this.doc.setPage(i);

            // Save current state
            this.doc.saveGraphicsState();

            // Watermark settings
            this.doc.setFontSize(60);
            this.doc.setTextColor(200, 200, 200);  // Light gray
            this.doc.setFont('helvetica', 'bold');

            // Calculate center of page
            const centerX = this.pageWidth / 2;
            const centerY = this.pageHeight / 2;

            // Rotate and draw watermark text diagonally
            // jsPDF text with rotation using transformation
            const text = 'FREE TRIAL';
            const textWidth = this.doc.getTextWidth(text);

            // Draw at 45 degree angle using text with angle parameter
            this.doc.text(text, centerX - textWidth / 2, centerY, {
                angle: 45
            });

            // Add smaller "Upgrade to Pro" text below
            this.doc.setFontSize(16);
            this.doc.setTextColor(180, 180, 180);
            this.doc.text('Upgrade to Pro for clean reports', centerX, centerY + 30, { align: 'center' });

            this.doc.restoreGraphicsState();
        }
    }
}

export default ReportGenerator;
